name: Notify Slack
on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: |
            *${{ github.repository }} - #${{ github.run_number }}* Started by user ${{ github.actor }} (Open)
            *Status: ${{ github.event.workflow_run.conclusion }} after ${{ (github.event.workflow_run.run_duration_ms // 1000) | round }} sec*
            ${{ github.event.workflow_run.head_commit.message }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
