name: Notify Slack
on:
  workflow_run:
    workflows: ["Build and Analyze"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build and Analyze
          run_id: ${{ github.event.workflow_run.id }}
          name: build-time
          path: artifacts

      - name: Read and convert build time
        id: read_build_time
        run: |
          BUILD_TIME=$(cat artifacts/build_time.txt)
          # Convert HH:MM:SS to seconds
          TIME_SECONDS=$(echo $BUILD_TIME | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
          echo "The build time stored in Workflow 1 was: $TIME_SECONDS"
          echo "build_time_seconds=$TIME_SECONDS" >> $GITHUB_OUTPUT
      - name: Notify Slack
        uses: 8398a7/action-slack@v3 
        with:
          fields: none
          status: ${{ github.event.workflow_run.conclusion }}
          text: |
            *${{ github.repository }} - #${{ github.run_number }}* Started by user ${{ github.actor }}
            *${{ github.repository }} - #${{ github.run_number }}* ${{ github.event.workflow_run.conclusion }} after ${{ steps.read_build_time.outputs.build_time_seconds }} sec
            *${{ github.repository }} - #${{ github.run_number }}* *Changes:*
            ${{ github.event.workflow_run.head_commit.message }}
            Deployment status: ${{ job.status }}
            Duration: ${{ env.duration }} seconds
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
