name: Notify Slack
on:
  workflow_run:
    workflows: ["Build and Analyze"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build and Analyze
          run_id: ${{ github.event.workflow_run.id }}
          name: build-time
          path: artifacts

      - name: Read and convert build time
        id: read_build_time
        run: |
          BUILD_TIME=$(cat artifacts/build_time.txt)
          # Convert HH:MM:SS to seconds
          TIME_SECONDS=$(echo $BUILD_TIME | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
          echo "The build time stored in Workflow 1 was: $TIME_SECONDS"
          echo "build_time_seconds=$TIME_SECONDS" >> $GITHUB_OUTPUT

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-message: >
            {
              "text": "*${{ github.repository }} - #${{ github.run_number }}* \n
              *Started by:* ${{ github.actor }}\n
              *Status:* ${{ job.status }}\n
              *Conclusion:* ${{ github.event.workflow_run.conclusion }} after ${{ steps.read_build_time.outputs.build_time_seconds }} sec\n
              *Changes:* ${{ github.event.workflow_run.head_commit.message }}\n
              *Deployment status:* ${{ job.status }}\n
              *Duration:* ${{ env.duration }} seconds"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
