name: Notify Slack
on:
  workflow_run:
    workflows: ["Build and Analyze"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: Build and Analyze
          run_id: ${{ github.event.workflow_run.id }}
          name: build-time
          path: artifacts

      - name: Read and display build time
        run: |
          BUILD_TIME=$(cat artifacts/build_time.txt)
          echo "The build time stored in Workflow 1 was: $BUILD_TIME"

      - name: Notify Slack
        uses: 8398a7/action-slack@v3 
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          text: |
            *${{ github.repository }} - #${{ github.run_number }}* Started by user ${{ github.actor }}
            *Changes:*
            ${{ github.event.workflow_run.head_commit.message }}
            *Build Time:* ${{ env.BUILD_TIME }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_TIME: ${{ steps.read_build_time.outputs.build_time }}
        if: always()
