name: Notify Slack
on:
  workflow_run:
    workflows: ["Build and Analyze"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: List available artifacts
        run: |
          echo "Available Artifacts:"
          ls -al $GITHUB_WORKSPACE

      - name: Download build time artifact
        uses: actions/download-artifact@v4
        with:
          name: build-time

      - name: Read and display build time
        run: |
          BUILD_TIME=$(cat build_time.txt)
          echo "The build time stored in Workflow 1 was: $BUILD_TIME"

      - name: Notify Slack
        uses: 8398a7/action-slack@v3 
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          text: |
            *${{ github.repository }} - #${{ github.run_number }}* Started by user ${{ github.actor }}
            *Changes:*
            ${{ github.event.workflow_run.head_commit.message }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
